default:
  image: python:3.10

stages:
  - lint
  - test
  - build
  - deploy
  
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

# Linting stage to check code style with Black
lint:
  stage: lint
  script:
    - pip install black
    - black --check --diff .
  allow_failure: false

# Testing stage to run your tests
test:
  stage: test
  script:
    - pip install -e .[test]
    - pytest -v --junitxml=report.xml --cov=wejax --cov-report=term --cov-report xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    when: always
    paths:
      - report.xml
      - coverage.xml
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  allow_failure: false


# Building the package stage
build:
  stage: build
  script:
    - pip install setuptools wheel build
    - python -m build --sdist --wheel
    - ls -l dist/
  artifacts:
    expire_in: 1 week
    paths:
      - dist/*
  allow_failure: false

pypi:
  # publish the source distribution on https://pypi.org/project/stardiceonline/, only when
  # a new tag
  stage: deploy
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - pip install twine
    - twine upload --non-interactive --repository pypi dist/*
    
# Optional: Publish to PyPI (This step is commented out and should only be enabled for your main branch or when you're ready to publish)
#publish:
#  stage: deploy
#  image: python:3.9
#  script:
#    - pip install twine
#    - twine upload --repository-url ${PYPI_REPOSITORY_URL} -u __token__ -p ${PYPI_API_TOKEN} dist/*
#  only:
#    - main  # or your release branch name
#  environment:
#    name: production